### ISSUE TITLE
filter not working with number

### ISSUE THREAD

**Issue by Pankraz76** [ExmgElements/exmg-paper-datatable#5]
I have an exmg-paper-data-filter included in my table. If I add a property to the filter-fields that´s an number the filtering does not work anymore. After changed my data to be always a stiring itw working fine again.

**Comment by Pankraz76** [comment]
this.rawItems.forEach(o => {
      filterFields.some(p => o[p].indexOf(this.filterValue) !== -1) && items.push(o);
    }); 

heres the bug. o[p] can return a number property which does not have the method indexOf. So a cast to string would be necessary i guess.

**Comment by marksmits** [comment]
Sorry for the slow but i just pushed a fix in version @exmg/exmg-paper-datatable@3.0.4

**Comment by marksmits** [comment]
Closing issue

**Comment by Pankraz76** [comment]
fixed, thx.
